[Distribution]
Distribution=arch
Architecture=x86-64

[Build]
ToolsTree=default
CacheDirectory=mkosi.cache
Incremental=yes

[Output]
OutputDirectory=mkosi.output
Format=disk
ImageId=AstrOS
Output=%i_%v_%a
SplitArtifacts=uki,partitions

[Content]
Hostname=astros-????-????
Bootable=yes
KernelCommandLine=
  mount.usr=dissect
  rw
KernelInitrdModules=
  default
  xhci_hcd
  xhci_pci
  uas
UnifiedKernelImageFormat=%i_%v_%a

[Validation]
SecureBoot=yes
SignExpectedPcr=yes
