[Distribution]
Distribution=arch
Repositories=multilib
Architecture=x86-64

[Build]
ToolsTree=default
CacheDirectory=mkosi.cache
Incremental=yes

[Output]
OutputDirectory=mkosi.output
Format=disk
ImageId=AstrOS
Output=%i_%v_%a
SplitArtifacts=uki,partitions
CompressOutput=zstd

[Content]
BaseTrees=%O/base_%v
Hostname=astros-????-????
Bootable=yes
Splash=/usr/share/astros/splash-astros.bmp
KernelCommandLine=
  root=dissect
  mount.usr=dissect
  rw
  systemd.mask=systemd-firstboot.service
  quiet
  systemd.image_policy=esp=unprotected:xbootldr=unprotected+unused+absent:usr=signed:root=encrypted+absent:home=absent:swap=encrypted+unused+absent:=ignore
  systemd.image_filter=usr=AstrOS_*:usr-verity=AstrOS_*:usr-verity-sig=AstrOS_*:root=AstrOS-*
  loglevel=3
  lsm=landlock,lockdown,yama,integrity,apparmor,bpf
KernelInitrdModules=
  default
  xhci_hcd
  xhci_pci
  uas
UnifiedKernelImageFormat=%i_%v_%a

[Validation]
SecureBoot=yes
SignExpectedPcr=yes
SecureBootAutoEnroll=no
