[Content]
Packages=
  base
  linux
  linux-firmware
  sof-firmware
  systemd
  zstd
  amd-ucode
  intel-ucode
  sudo
  libnewt
  qrencode
  qemu-guest-agent
  spice-vdagent
  efibootmgr
  openssh
  tpm2-tss
  steam-devices
