[Content]
RemoveFiles=
  # pacman
  /usr/bin/pacman
  /usr/bin/pacman-conf
  /usr/bin/pacman-db-upgrade
  /usr/bin/pacman-key
  /usr/bin/makepkg
  /usr/share/pacman
  /etc/pacman.conf
  /etc/pacman.d/

  # menu clutter
  /usr/share/applications/avahi-discover.desktop
  /usr/share/applications/bssh.desktop
  /usr/share/applications/bvnc.desktop
  /usr/share/applications/lstopo.desktop
  /usr/share/applications/nm-connection-editor.desktop
  /usr/share/applications/qt6ct.desktop
  /usr/share/applications/qv4l2.desktop
  /usr/share/applications/qvidcap.desktop
  /usr/share/applications/tuned-gui.desktop
  /usr/share/applications/vim.desktop
