[Content]
Packages=
  apparmor
  cups
  cups-pdf
  ipp-usb
  avahi
  bluez
  pipewire
  pipewire-pulse
  pipewire-jack
  pipewire-zeroconf
  wireplumber
  tuned-ppd
  upower
  zram-generator
  networkmanager
  fwupd
