[Output]
# No SplitArtifacts required here
SplitArtifacts=
Format=directory

[Content]
CleanPackageMetadata=no
Bootable=no
Packages=
  base
  linux
  linux-firmware
  sof-firmware
  systemd
  zstd
  amd-ucode
  intel-ucode
  btrfs-progs
  dosfstools
  exfatprogs
  e2fsprogs
  xfsprogs
  ntfs-3g
  ntfsprogs
  erofs-utils
  networkmanager
  vim
  man-db
  bash-completion
  sudo
  git
  noto-fonts
  noto-fonts-emoji
  noto-fonts-cjk
  libnewt
  qrencode
  vulkan-radeon
  vulkan-intel
  vulkan-virtio
  vulkan-swrast
  vulkan-tools
  intel-media-driver
  qemu-guest-agent
  spice-vdagent
  fwupd
  rsync
  gptfdisk
  efibootmgr
  openssh
  tpm2-tss

  # added until cosmic-player-flatpak exists
  cosmic-player
  gstreamer
  gst-libav
  gst-plugin-pipewire
  gst-plugin-va
  gst-plugins-bad
  gst-plugins-base
  gst-plugins-good
  gst-plugins-ugly

  cosmic-app-library
  cosmic-applets
  cosmic-bg
  cosmic-comp
  cosmic-files
  cosmic-greeter
  cosmic-idle
  cosmic-initial-setup
  cosmic-launcher
  cosmic-monitor
  cosmic-notifications
  cosmic-osd
  cosmic-panel
  cosmic-randr
  cosmic-screenshot
  cosmic-session
  cosmic-settings
  cosmic-settings-daemon
  cosmic-sound-theme
  cosmic-store
  cosmic-terminal
  cosmic-text-editor
  cosmic-wallpapers
  cosmic-workspaces
  xdg-desktop-portal-cosmic
  xdg-desktop-portal-gtk
  xdg-user-dirs

  gnome-disk-utility
  gvfs
  gvfs-dnssd
  gvfs-nfs
  gvfs-smb
  gvfs-afc
  gvfs-mtp
  gvfs-gphoto2
  gnome-keyring

  cups
  avahi
  bluez
  pipewire
  pipewire-jack
  pipewire-zeroconf
  tuned-ppd
  upower
  zram-generator

  distrobox
  podman
  flatpak

RemoveFiles=
  /usr/bin/pacman
  /usr/bin/pacman-conf
  /usr/bin/pacman-db-upgrade
  /usr/bin/pacman-key
  /usr/bin/makepkg
  /usr/share/pacman
  /etc/pacman.conf
  /etc/pacman.d/
