[Content]
Packages=
  base
  linux
  linux-firmware
  amd-ucode
  intel-ucode
  btrfs-progs
  dosfstools
  exfatprogs
  e2fsprogs
  xfsprogs
  erofs-utils
  networkmanager
  vim
  man-db
  systemd-ukify
  bash-completion
  sudo
  noto-fonts
  noto-fonts-emoji
  vulkan-radeon
  vulkan-intel
  nvidia-utils
  vulkan-tools

  cosmic-app-library
  cosmic-applets
  cosmic-bg
  cosmic-comp
  cosmic-files
  cosmic-greeter
  cosmic-idle
  cosmic-initial-setup
  cosmic-launcher
  cosmic-monitor
  cosmic-notifications
  cosmic-osd
  cosmic-panel
  cosmic-randr
  cosmic-screenshot
  cosmic-session
  cosmic-settings
  cosmic-settings-daemon
  cosmic-store
  cosmic-terminal
  cosmic-text-editor
  cosmic-wallpapers
  cosmic-workspaces
  xdg-desktop-portal-cosmic
  xdg-desktop-portal-gtk
  xdg-user-dirs

  gnome-disk-utility
  gvfs
  gvfs-dnssd
  gvfs-nfs
  gvfs-smb
  gnome-keyring

  bluez
  tuned-ppd
  upower
  zram-generator
