[Content]
Packages=
	base
	linux
	linux-firmware
  amd-ucode
  intel-ucode
  btrfs-progs
  dosfstools
  exfatprogs
  e2fsprogs
  xfsprogs
  erofs-utils
  networkmanager
  vim
  man-db
  systemd-ukify

  git
  mkosi
