[UKIProfile]
Profile=
  ID=live
  TITLE=Live (installer)

Cmdline=
  mount.usr=dissect
  rw
  root=tmpfs
  rd.systemd.mask=systemd-repart.service
  systemd.mask=systemd-repart.service
  systemd.mask=cosmic-greeter.service
  systemd.set-credential=passwd.plaintext-password.root:AstrOS
  systemd.set-credential=agetty.autologin:root
  systemd.set-credential=login.noauth:yes
  SYSTEMD_SULOGIN_FORCE=1

SignExpectedPcr=no
