when:
  - event: push
    branch: main
  - event: cron
    branch: main
  - event: manual
    branch: main

steps:
  - name: build system
    image: docker.io/library/archlinux
    commands:
      - umask 022
      - chmod -R go-w .
      - pacman -Syu --noconfirm mkosi
      - cd system
      - printf '%s' "$MKOSI_KEY" > mkosi.key
      - printf '%s' "$MKOSI_CRT" > mkosi.crt
      - chmod 0600 mkosi.key mkosi.crt
      - mkosi -f -B --workspace-directory=/woodpecker/mkosi.workspace
    environment:
      MKOSI_KEY:
        from_secret: mkosi.key
      MKOSI_CRT:
        from_secret: mkosi.crt

  - name: build installer
    image: docker.io/library/archlinux
    commands:
      - umask 022
      - pacman -Syu --noconfirm mkosi
      - cp ./system/mkosi.version ./installer/
      - cp ./system/mkosi.output/AstrOS*_x86-64.raw.zst ./installer/mkosi.extra/images/AstrOS.raw.zst
      - cd installer
      - mkosi -f --workspace-directory=/woodpecker/mkosi.workspace

  - name: deploy
    image: docker.io/library/archlinux
    commands:
      - pacman -Syu --noconfirm --needed rclone gnupg

      # preparation
      - rm -f ./system/mkosi.output/initrd*
      - rm -rf ./system/mkosi.output/base*
      - mv ./installer/mkosi.output/AstrOS-installer*_x86-64.raw.zst ./system/mkosi.output
      - cd ./system/mkosi.output
      - cp AstrOS-installer*.raw.zst AstrOS-installer_latest_x86-64.raw.zst
      - sha256sum -- * > SHA256SUMS
      - printf '%s' "$GPG_KEY" | gpg --batch --import
      - gpg --batch --yes --pinentry-mode loopback --detach-sign --armor -o SHA256SUMS.asc SHA256SUMS

      # deploy
      - mkdir -p ~/.config/rclone
      - printf '%s' "$RCLONE" > ~/.config/rclone/rclone.conf
      - chmod 0600 ~/.config/rclone/rclone.conf
      - rclone sync . r2:astros-dl --stats 5s --stats-one-line --exclude 'SHA256SUMS*'
      - rclone copy . r2:astros-dl --include 'SHA256SUMS*'
    environment:
      GPG_KEY:
        from_secret: gpg_key
      RCLONE:
        from_secret: rclone
