when:
  - event: push
    branch: main
  - event: cron
    branch: main
  - event: manual
    branch: main

steps:
  - name: build system
    image: docker.io/library/archlinux
    commands:
      - umask 022
      - chmod -R go-w .
      - pacman -Syu --noconfirm mkosi
      - cd system
      - printf '%s' "$MKOSI_KEY" > mkosi.key
      - printf '%s' "$MKOSI_CRT" > mkosi.crt
      - chmod 0600 mkosi.key mkosi.crt
      - mkosi -f -B --workspace-directory=/woodpecker/mkosi.workspace
    environment:
      MKOSI_KEY:
        from_secret: mkosi.key
      MKOSI_CRT:
        from_secret: mkosi.crt

  - name: build installer
    image: docker.io/library/archlinux
    commands:
      - umask 022
      - pacman -Syu --noconfirm mkosi
      - cp ./system/mkosi.version ./installer/
      - zstd -o ./installer/mkosi.extra/images/AstrOS.raw.zst ./system/mkosi.output/AstrOS*_x86-64.raw
      - cd installer
      - mkosi -f --workspace-directory=/woodpecker/mkosi.workspace

  - name: deploy
    image: docker.io/library/archlinux
    commands:
      - pacman -Syu --noconfirm --needed rsync gnupg
      - rm -f ./system/mkosi.output/initrd*
      - rm -rf ./system/mkosi.output/base*
      - mv ./installer/mkosi.output/AstrOS-installer*_x86-64.raw.zst ./system/mkosi.output
      - cd ./system/mkosi.output
      - ln -sf AstrOS-installer*.raw.zst AstrOS-installer_latest_x86-64.raw.zst
      - sha256sum -- AstrOS* > SHA256SUMS
      - printf '%s' "$GPG_KEY" | gpg --batch --import
      - gpg --batch --yes --pinentry-mode loopback --detach-sign --armor -o SHA256SUMS.asc SHA256SUMS
      - cd ..
      - rsync -aP --delete --copy-unsafe-links mkosi.output/ /mnt
    volumes:
      - /srv/astros/dl-astros:/mnt:z
    environment:
      GPG_KEY:
        from_secret: gpg_key
