[Distribution]
Distribution=arch
Architecture=x86-64

[Build]
ToolsTree=default
CacheDirectory=mkosi.cache
Incremental=yes

[Output]
OutputDirectory=mkosi.output
Format=disk
ImageId=AstrOS-installer
Output=%i_%v_%a
CompressOutput=zstd

[Content]
Hostname=astros-installer
Bootable=yes
KernelCommandLine=
  mount.usr=dissect
  rw
  root=tmpfs
  systemd.mask=systemd-firstboot.service
  quiet
  loglevel=3
  SYSTEMD_SULOGIN_FORCE=1
KernelInitrdModules=
  default
  xhci_hcd
  xhci_pci
  uas
Packages=
  base
  linux
  zstd
  libnewt
